spring:  
  application:  
    name: microcloud-config-client

server:
  port: 8101

eureka:
  client:
    serviceUrl:
      defaultZone: http://ws:hello@eureka-7001.com:7001/eureka/,http://ws:hello@eureka-7002.com:7002/eureka/
      register-with-eureka: false