spring:  
  application:  
    name: microcloud-config-client

server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: http://ws:hello@eureka-7002.com:7002/eureka/,http://ws:hello@eureka-7003.com:7003/eureka/
      register-with-eureka: false