spring:
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  server:
    renewal-percent-threshold: 0.4
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: true # false 关闭保护模式
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ws:hello@eureka7001.com:7001/eureka/